Adding LastRunTime and NextRunTime to Manage Page
Brightspace/custom-ads-scheduler pull request #63
Opened 2020-12-03 01:10 UTC by Syeda-Azim

2020-12-03 13:09 UTC, lweber-d2l approved these changes

2020-12-03 13:13 UTC, lweber-d2l requested changes
One test needs updating as it is expecting start/end dates:

✖ 1 test failed
FAILED TESTS:
  d2l-manage-schedules
    serialize schedules
      ✖ binds correct values in table
        Chrome Headless 86.0.4240.198 (Linux x86_64)
      AssertionError: expected 'NaN/NaN/NaN NaN:NaN AM' to include '9/1/2020 12:00 AM - 12/31/2020 12:00 AM'
      + expected - actual
    at Context.<anonymous> (test/d2l-manage-schedules.test.js:81:36)

2020-12-03 14:23 UTC, JeremyWinkler commented on src/components/d2l-manage-schedules.js
> +				<td>${ this._formatDateTime(schedule.lastRunTime) }</td>
Assuming we change lastRunTime to a nullable field like in my comment in the other PR, we would need to update this to account for if it is null.

2020-12-03 15:23 UTC, lweber-d2l approved these changes

2020-12-03 15:29 UTC, JeremyWinkler commented on lang/en.js
> -	'logs.unavailableDate': 'N/A',
The logs page was using this. Could you update the log page to use the new one?
https://github.com/Brightspace/custom-ads-scheduler/blob/master/src/components/d2l-schedule-logs.js#L134

2020-12-04 00:30 UTC, Syeda-Azim commented on src/components/d2l-manage-schedules.js
> +				<td>${ this._formatDateTime(schedule.lastRunTime === schedule.nextRunTime ? null : schedule.lastRunTime) }</td>
We decided for lastRunTime column to be NOT NULL in DB. So, on Schedule creation we are storing nextRunTime in lastRunTime column and showing N/A in the UI.

2020-12-04 16:44 UTC, Syeda-Azim commented on src/components/d2l-manage-schedules.js
> +				<td>${ this._formatDateTime(schedule.lastRunTime === schedule.nextRunTime ? null : schedule.lastRunTime) }</td>
Reverting LastRunTime to nullable column.

2020-12-07 17:07 UTC, lweber-d2l approved these changes

2020-12-07 17:19 UTC, merged